apiVersion: v1
kind: Pod
metadata:
  name: static-web              ## имя пода
  namespace: lesson14           ## имя ns
  labels:
    app: goweb                  ## вешаем на Под ярлык (метку) app=goweb
spec:
  containers:
    - name: web                 ## имя контейнера в поде (контейнеров может быть несколько)
      image: ku22/lesson1:v0.2  ## образ для контейнера web
                                ## укажите здесь свой образ из предыдущих уроков в формате 
                                ## image: <имя_пользователя>/<репозиторий>/<тег>
      ports:
        - name: web
          containerPort: 8080   ## открыли у контейнера порт
          protocol: TCP
